parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lipoti\Shop\Admin\Controller\:
    resource: '../../src/Admin/Controller'
    public: true

  Lipoti\Shop\Admin\Widget\:
    resource: '../../src/Admin/Widget'
    public: true

  Lipoti\Shop\Admin\Security\LoginFormAuthenticator: ~

  Lipoti\Shop\Admin\Form\TranslationArrayNameKeyType:
    arguments:
      $locales: '%locales%'
  # VendorName\ProjectName\Core\ServiceName: ~
