parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lipoti\Shop\Admin\Controller\:
    resource: '../../src/Admin/Controller'
    public: true


  Lipoti\Shop\Admin\Form\TranslationArrayNameKeyType:
    arguments:
      $locales: '%locales%'

  Lipoti\Shop\Admin\Mapper\Catalog\CategoryEntityToCategoryEditDtoMapper: ~

  Lipoti\Shop\Admin\Security\LoginFormAuthenticator: ~

  Lipoti\Shop\Admin\Widget\:
    resource: '../../src/Admin/Widget'
    public: true
  # VendorName\ProjectName\Core\ServiceName: ~
