parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lipoti\Shop\Category\Controller\:
    resource: '../../src/Category/Controller'
    public: true

  Lipoti\Shop\Category\Repository\:
    resource: '../../src/Category/Repository'
    public: true