parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lipoti\Shop\Category\Controller\:
    resource: '../../src/Category/Controller'
    public: true

#   Lipoti\Shop\Category\Controller\Parts\CategoryNavController: ~
  # VendorName\ProjectName\Core\ServiceName: ~