parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lipoti\Shop\Core\Controller\:
        resource: '../../src/Core/Controller'
        public: true

    # VendorName\ProjectName\Core\ServiceName: ~
