parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lipoti\Shop\Core\Controller\:
    resource: '../../src/Core/Controller'
    public: true

  Lipoti\Shop\Core\DataFixtures\:
    resource: '../../src/Core/DataFixtures'

  Lipoti\Shop\Core\DataFixtures\CategoryFixtures:
    arguments:
      $locales: '%locales%'

  Lipoti\Shop\Core\Repository\:
    resource: '../../src/Core/Repository'

  Lipoti\Shop\Core\Manager\:
    resource: '../../src/Core/Manager'

  Lipoti\Shop\Core\Validator\Constraints\UniqueDTOPropertyValidator: ~

  Lipoti\Shop\Core\Widget\HeaderDropdownCategory\HeaderDropdownCategoryController: ~
  Lipoti\Shop\Core\Widget\HeaderDropdownCategory\HeaderDropdownCategoryHandler: ~

#  Lipoti\Shop\Category\Controller\Parts\CategoryNavController: ~
  # VendorName\ProjectName\Core\ServiceName: ~
