artgris_file_manager:
  conf:
    default:
      dir: '%kernel.project_dir%/public/uploads'
    files:
      dir: "%kernel.project_dir%/public/uploads"
      type: 'file'
    images:
      dir: "%kernel.project_dir%/public/uploads"
      type: 'image'