controllers:
  resource: ../../src/User/Controller/
  type: annotation

user_user_registration:
  path: /{_locale<%app.supported_locales%>}/registration
  controller: Lipoti\Shop\User\Controller\Registration\RegistrationController

user_user_registration_success:
  path: /{_locale<%app.supported_locales%>}/registration-success
  controller: Lipoti\Shop\User\Controller\Registration\RegistrationSuccessController