parameters:
    info_email: 'fabien@example.com'
    locales: ['uk', 'en']
    default_locale: 'uk'
    kernel.secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
