admin_catalog_category_list:
  path: /admin/category-list
  controller: Lipoti\Shop\Admin\Controller\Catalog\Category\CategoryListController

admin_catalog_category_create:
  path: /admin/category-create
  controller: Lipoti\Shop\Admin\Controller\Catalog\Category\CategoryCreateController

admin_catalog_category_edit:
  path: /admin/category-edit/{id}
  controller: Lipoti\Shop\Admin\Controller\Catalog\Category\CategoryEditController

admin_catalog_product_list:
  path: /admin/product-list
  controller: Lipoti\Shop\Admin\Controller\Catalog\Product\ProductListController

admin_catalog_product_create:
  path: /admin/product-create
  controller: Lipoti\Shop\Admin\Controller\Catalog\Product\ProductCreateController

admin_catalog_product_edit:
  path: /admin/product-edit
  controller: Lipoti\Shop\Admin\Controller\Catalog\Product\ProductEditController