admin_catalog_category_list:
  path: /admin/category-list
  controller: Lipoti\Shop\Admin\Controller\Catalog\Category\CategoryListController

admin_catalog_category_edit:
  path: /admin/category-edit
  controller: Lipoti\Shop\Admin\Controller\Catalog\Category\CategoryEditController